version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - word-arena

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///app/data/word_arena.db
      - RUST_LOG=info
    volumes:
      - backend_data:/app/data
      - ./word_lists:/app/word_lists:ro
    networks:
      - word-arena

volumes:
  backend_data:

networks:
  word-arena:
    driver: bridge