version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "3000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - word-arena
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "80"
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - word-arena

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - "DATABASE_URL=sqlite::memory:"
      - RUST_LOG=info
      - WORDS_DIRECTORY=/app/word_lists
      - HOST=0.0.0.0
    networks:
      - word-arena

networks:
  word-arena:
    driver: bridge
