[package]
name = "game-core"
version = "0.1.0"
edition = "2024"

[dependencies]
game-types = { path = "../game-types" }
serde = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
